In [ ]:
import pandas as pd
df = pd.read_csv('energy_database.csv')
df

In [ ]:
df['GDP_Per_Capita'] = df['GDP']/df['POPESTIMATE']*1E6

In [ ]:
df['Electrical_Consumption_Per_Capita'] = df['ElecC']/df['POPESTIMATE']*1E6

In [ ]:
df['Energy_Per_Capita'] = df['TotalC']/df['POPESTIMATE']*1E6

In [ ]:
df['Spend_per_Capita'] = df['TotalE']/df['POPESTIMATE']*1E6

In [31]:
production = pd.read_csv('production.csv')

In [32]:
consumption = pd.read_csv('consumption.csv')

In [35]:
df.loc[df['State'] == 'United States']

,State,Year,TotalC,TotalP,TotalE,TotalPrice,BiomassC,CoalC,CoalP,CoalE,...,NatGasPrice,LPGC,LPGE,LPGPrice,GDP,POPESTIMATE,GDP_Per_Capita,Electrical_Consumption_Per_Capita,Energy_Per_Capita,Spend_per_Capita
255,United States,2010,97446021.0,74593106.0,1212094.3,18.92,4235786.0,20828382.0,21831301.0,50473.7,...,7.37,2820984.0,54706.5,19.45,14859772.50,309347057.0,48035.926522,41414.711115,315005.489126,3918.234464
256,United States,2011,96827465.0,77778786.0,1393001.3,21.88,4290667.0,19663856.0,22057248.0,50440.5,...,7.03,2838955.0,65197.2,23.00,15406000.25,311721632.0,49422.300760,41044.552853,310621.577267,4468.734785
257,United States,2012,94411432.0,79032062.0,1356103.6,21.85,4249844.0,17380923.0,20585319.0,45245.1,...,5.74,2911810.0,50772.0,17.47,16041239.75,314112078.0,51068.522586,40132.633805,300566.067377,4317.260287
258,United States,2013,97141368.0,81604540.0,1378359.7,21.45,4464695.0,18038771.0,19901802.0,45516.6,...,6.44,3166737.0,55075.0,17.42,16548795.25,316497531.0,52287.280718,40155.918310,306926.147869,4355.040924
259,United States,2014,98385210.0,87228228.0,1394974.0,21.33,4611638.0,17996577.0,20170837.0,45118.9,...,7.20,3090053.0,58652.3,19.03,17233140.00,318857056.0,54046.600744,40285.001565,308555.850180,4374.919651

In [37]:
state_data = df.loc[df['State'] != 'United States']

In [38]:
national_data = df.loc[df['State'] == 'United States']

In [51]:
def break_out_national(df):
    national = df.loc[df['State'] == 'United States']
    all_states = df.loc[(df['State'] != 'United States')]
    only_states = all_states.loc[all_states['State'] != 'District of Columbia']
                        
    return (only_states, national )
(state_data, national_data) = break_out_national(df)
(state_production, national_production) = break_out_national(production)
(state_consumption, national_consumption) = break_out_national(production)

In [41]:
from galyleo.galyleo_table import GalyleoTable
from galyleo.galyleo_jupyterlab_client import GalyleoClient

In [42]:
def send_dataframe_to_dashboard(dataframe, table_name, client):
    table = GalyleoTable(table_name)
    table.load_from_dataframe(dataframe)
    client.send_data_to_dashboard(table)

In [43]:
client = GalyleoClient()

In [52]:
send_dataframe_to_dashboard(state_data, 'State Data', client)
send_dataframe_to_dashboard(national_data, 'National Data', client)
send_dataframe_to_dashboard(state_production, 'State Production', client)
send_dataframe_to_dashboard(national_production, 'National Production', client)
send_dataframe_to_dashboard(state_production, 'State Consumption', client)
send_dataframe_to_dashboard(national_production, 'National Consumption', client)

In [48]:
state_data.loc[state_data['GDP_Per_Capita'] > 100000]

,State,Year,TotalC,TotalP,TotalE,TotalPrice,BiomassC,CoalC,CoalP,CoalE,...,NatGasPrice,LPGC,LPGE,LPGPrice,GDP,POPESTIMATE,GDP_Per_Capita,Electrical_Consumption_Per_Capita,Energy_Per_Capita,Spend_per_Capita
250,District of Columbia,2010,190529.0,95.0,2497.5,25.76,1027.0,71.0,0.0,0.2,...,12.41,21.0,0.6,28.26,104044.75,605210.0,171915.120371,66958.576362,314814.692421,4126.666777
251,District of Columbia,2011,183806.0,271.0,2453.0,26.66,1028.0,48.0,0.0,0.2,...,11.91,18.0,0.5,29.64,108029.00,620427.0,174120.404173,63585.240488,296257.255084,3953.728642
252,District of Columbia,2012,172963.0,277.0,2218.2,25.50,819.0,77.0,0.0,0.2,...,11.18,27.0,0.7,27.11,109760.00,635040.0,172839.506173,60492.252457,272365.520282,3493.008314
253,District of Columbia,2013,175560.0,323.0,2229.1,24.63,855.0,4.0,0.0,0.0,...,11.43,25.0,0.7,28.24,111816.50,649111.0,172260.984639,58270.465298,270462.216786,3434.081382
254,District of Columbia,2014,178929.0,360.0,2320.3,24.96,920.0,48.0,0.0,0.1,...,12.11,24.0,0.8,32.28,116539.25,658893.0,176871.282591,57965.405612,271560.025679,3521.512598